spring:
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/jiakao?serverTimezone=GMT%2B8

server:
  port: 8888

logging:
  level:
    top.imono.jk.mapper: debug
jk:
  cfg:
    cors-origins:
      - "*"
