spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null # 非空的属性才能出现在json中
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 10
          # 最大空闲连接
          max-idle: 50
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000


mybatis-plus:
  type-aliases-package: top.imono.jk.pojo
  global-config:
    db-config:
      id-type: auto  #主键策略
  # 起别名
  configuration:
    use-generated-keys: true

