spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null # 非空的属性才能出现在json中



mybatis-plus:
  type-aliases-package: top.imono.jk.pojo
  global-config:
    db-config:
      id-type: auto  #主键策略
  # 起别名
  configuration:
    use-generated-keys: true

