spring:
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/jiakao?serverTimezone=GMT%2B8
  data:
      redis:
        host: 127.0.0.1
        port: 6379
        database: 1
        # 读超时
        timeout: 3000
        # 连接超时
        connectTimeout: 5000
        # Lettuce连接池
        lettuce:
          pool:
            # 最小空闲连接
            min-idle: 10
            # 最大空闲连接
            max-idle: 50
            # 最大连接数
            max-active: 100
            # 连接分配应该阻塞的最大时间
            max-wait: 2000

server:
  port: 8888
springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    top.imono.jk.mapper: debug
jk:
  cfg:
    cors-origins:
      - "*"

